version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - echo "Configuring Serverless Framework with license key"
      - serverless config credentials --provider aws --key $SERVERLESS_ACCESS_KEY
  build:
    commands:
      - echo "Starting serverless deployment"
      - serverless deploy --stage $ENVIRONMENT --region $REGION --conceal --verbose
      - echo "Finished deployment"
