service: ragAPI

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  timeout: 600

plugins:
  - serverless-offline

package:
  individually: false
  exclude:
    - node_modules/**
    - .vscode/**
    - .env
    - .gitignore
    - env/**

  include:
    - src/

functions:
  retrieve-function:
    handler: src/lambdas/backend/handler.lambda_handler
    events:
      - http:
          path: /retrieve
          method: post

  embbedings-function:
    handler: src/lambdas/embbedings/handler.lambda_handler
    events:
      - s3:
          bucket: my-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .txt

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-bucket
        NotificationConfiguration:
          LambdaConfigurations:
            -
              Event: s3:ObjectCreated:*
              Function: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:s3-lambda-service-dev-s3Handler
