service: ragAPI

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  iam:
    role: arn:aws:iam::552516487395:role/rag-api-role

plugins:
  - serverless-offline

package:
  individually: false
  exclude:
    - node_modules/**
    - .vscode/**
    - .env
    - .gitignore
    - env/**

  include:
    - src/

functions:
  retrieve-function:
    handler: src/lambdas/backend/handler.lambda_handler
    events:
      - http:
          path: /retrieve
          method: post

  embbedings-function:
    handler: src/lambdas/embbedings/handler.lambda_handler

